BOARD_TAG = pro5v328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = Adafruit_GFX Adafruit_SSD1306 SPI RF24
ARDUINO_SKETCHBOOK = /home/torsten/Arduino/
CXXFLAGS_STD=-std=c++11

include /usr/share/arduino/Arduino.mk

