BOARD_TAG = nano
BOARD_SUB = atmega328old
ARDMK_VENDOR = arduino
AVRDUDE_CONF = /etc/avrdude.conf
USER_LIB_PATH = /home/torsten/Arduino/libraries
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = Adafruit_GFX_Library SPI RF24 Wire
ARDUINO_DIR = /opt/arduino-1.8.8
CXXFLAGS_STD=-std=c++11

include /usr/local/share/arduino/Arduino.mk

